### ISSUE TITLE
GPU does not work on both 'standard_gpu' and 'standard_p100' master types

### ISSUE THREAD

**Issue by fmannhardt** [rstudio/cloudml#174]
I am trying to run Tensorflow via cloudml using the CuDNNLSTM layer, but the CUDA version seem not to match on the image provided by R cloudml.

I get the following error messages:

```
I  master-replica-0 2018-07-20 23:08:14.088141: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE  master-replica-0
I  master-replica-0 2018-07-20 23:08:14.088227: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: cmle-training-master-9723cafe3e-0-hdlvp  master-replica-0
I  master-replica-0 2018-07-20 23:08:14.088245: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cmle-training-master-9723cafe3e-0-hdlvp  master-replica-0
I  master-replica-0 2018-07-20 23:08:14.088356: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.111.0  master-replica-0
I  master-replica-0 2018-07-20 23:08:14.088411: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 390.46.0  master-replica-0
I  master-replica-0 2018-07-20 23:08:14.088427: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 390.46.0 does not match DSO version 384.111.0 -- cannot find working devices in this configuration  master-replica-0
```

Also afterwards:

```
I  master-replica-0 Error in py_call_impl(callable, dots$args, dots$keywords) :   master-replica-0
I  master-replica-0   InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:  master-replica-0
I  master-replica-0   device='GPU'; T in [DT_DOUBLE]  master-replica-0
I  master-replica-0   device='GPU'; T in [DT_FLOAT]  master-replica-0
I  master-replica-0   device='GPU'; T in [DT_HALF]  master-replica-0
I  master-replica-0 	 [[Node: cu_dnnlstm_1/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](cu_dnnlstm_1/transpose, cu_dnnlstm_1/ExpandDims_1, cu_dnnlstm_1/ExpandDims_2, cu_dnnlstm_1/concat_1)]]  master-replica-0
I  master-replica-0 Caused by op u'cu_dnnlstm_1/CudnnRNN', defined at:  master-replica-0
I  master-replica-0   File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 500, in __call__  master-replica-0
I  master-replica-0     return super(RNN, self).__call__(inputs, **kwargs)  master-replica-0
I  master-replica-0   File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 460, in __call__  master-replica-0
I  master-replica-0     output = self.call(inputs, **kwargs)  master-replica-0
I  master-replica-0   File "/usr/local/lib/python2.7/dist-packages/keras/layers/cudnn_recurrent.py", line 90, in call  master-replica-0
I  master-replica-0     output, states = self._pr  master-replica-0
I  master-replica-0 Execution halted  master-replica-0
```

In the beginning of the log, I see that a GPU is provisioned:

```
I  master-replica-0 Running task with arguments: --cluster={"master": ["cmle-training-master-9723cafe3e-0:2222"]} --task={"type": "master", "index": 0, "trial": "1"} --job={
  "scale_tier": "CUSTOM",
  "master_type": "standard_gpu",
  "package_uris": ["gs://XXXXX/r-cloudml/staging/packages/936ce98470b4d1bce251a49a120ed60f67d7cb04886f86a9affefcff4e8ec052/cloudml-1.0.0.0.zip"],
  "python_module": "cloudml-model.cloudml.deploy",
  "args": ["Rscript"],
  "hyperparameters": {
    "goal": "MAXIMIZE",
    "params": [{
      "parameter_name": "dropout",
      "min_value": 0.05,
      "max_value": 0.5,
      "type": "DOUBLE",
      "scale_type": "UNIT_LINEAR_SCALE"
    }, {
      "parameter_name": "lstm_units",
      "type": "DISCRETE",
      "discrete_values": [64.0, 128.0, 256.0, 512.0]
    }, {
      "parameter_name": "dense_units",
      "type": "DISCRETE",
      "discrete_values": [32.0, 64.0, 128.0]
    }, {
      "parameter_name": "epochs",
      "min_value": 10.0,
      "max_value": 50.0,
      "type": "INTEGER",
      "scale_type": "UNIT_LINEAR_SCALE"
    }],
    "max_trials": 15,
    "hyperparameter_metric_tag": "accuracy",
    "enable_trial_early_stopping": true
  },
  "region": "us-central1",
  "runtime_version": "1.6",
  "job_dir": "gs://XXXXXX/r-cloudml/staging"
} --hyperparams={"dense_units":"32","dropout":"0.22395051373210084","epochs":"16","lstm_units":"512"} master-replica-0 
I  master-replica-0 Running module cloudml-model.cloudml.deploy. master-replica-0 
```

And

```
I  master-replica-0 +-----------------------------------------------------------------------------+ master-replica-0 
I  master-replica-0 | NVIDIA-SMI 384.111                Driver Version: 390.46                    | master-replica-0 
I  master-replica-0 |-------------------------------+----------------------+----------------------+ master-replica-0 
I  master-replica-0 | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC | master-replica-0 
I  master-replica-0 | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. | master-replica-0 
I  master-replica-0 |===============================+======================+======================| master-replica-0 
I  master-replica-0 |   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 | master-replica-0 
I  master-replica-0 | N/A   31C    P8    25W / 149W |      0MiB / 11441MiB |      0%      Default | master-replica-0 
I  master-replica-0 +-------------------------------+----------------------+----------------------+ master-replica-0 
```

Is this a problem with R cloudml or Google?

**Comment by jjallaire** [comment]
These are lower level CloudML GPU provisioning errors. I would take these to the normal CloudML support channels and see what the diagnosis is (pls link any correspondence back here though).

**Comment by fmannhardt** [comment]
Ok thanks, I was not sure if you are using some custom image that might cause the version mismatch between libcuda and the driver. I will report it to the CloudML support.

**Comment by jjallaire** [comment]
No, there is no custom image for R, it uses the same base TF image as the rest of CloudML.

**Comment by fmannhardt** [comment]
The issue has been confirmed and solved by Google. After updating my Google Cloud SDK the GPU is now used properly.
